num1 = int(input("enter first number: "))
num2 = int(input("enter second number: "))
print("Added: ", num1 + num2 )
print("Subtracted:", num1 - num2)
print("Multiplied:", num1 * num2)
print("Divided:", round(num1 / num2 , 2))